#!/bin/bash
#
# This script is designed to be run inside the container
#

# /usr/share/oem/cloud-config.yml
# fail hard and fast even on pipelines
# cat ~/.ssh/master.pub >> ~/.ssh/authorized_keys
#
# upload key to ESXI 5.1 for root user (/etc/ssh/keys-<user>/authorized_keys)
# cat ~/.ssh/id_rsa.pub | ssh root@IP "cat >> /etc/ssh/keys-root/authorized_keys"
set -eo pipefail

help() {
  echo ............................................................
  echo "Install CoreOS to ESXI Host"
  echo "Run : w-coreos install <WMvare Host> <CoreOS Host> [cache|clean]"
  echo "Example: w-coreos install esxi/vmware01.sh host/test01.sh"
  echo ............................................................
  echo "Run : w-coreos gen <CoreOS Host>"
  echo "Example: w-coreos gen host/test01.sh"
  echo ............................................................
  echo "Run : w-coreos deploy <CoreOS Host>"
  echo "Example: w-coreos deploy host/test01.sh"
  echo ............................................................
  echo "Run : w-coreos update <CoreOS Host>"
  echo "Example: w-coreos update host/test01.sh"
  echo ............................................................
  echo "Run : w-coreos ssh <CoreOS Host>"
  echo "Example: w-coreos ssh host/test01.sh"
  echo ............................................................
  exit 1
}
if [[ -z $1 ]]; then
  # is not set $1
  help
fi

mkdir -p ./keys
mkdir -p ./cloud-config
mkdir -p ./esxi
mkdir -p ./host

sshGet () {
  H_IP=${1}
  SSH_COMMAND=${3}
  if [[ -z ${2} ]]; then
    # echo "User key no set :("
    KEYF=insecure_ssh_key
  else
    if [[ ! -f ${2} ]]; then
      # echo "File no exits :( ${2}"
      KEYF=insecure_ssh_key
    else
      # echo "User key set :)"
      KEYF=${2}
    fi
  fi
  ssh -i ${KEYF} -o StrictHostKeyChecking=no core@${H_IP} -C ${SSH_COMMAND}
}

deployTools () {
  H_IP=${1}
  KEY_FILE=${2}
  TOOLS=${3}
  VT=vmtools-install.sh
  if [[ ! -z ${TOOLS} ]]; then
    if [[ -f ${TOOLS} ]]; then
      echo "Deploy VMware tools to $H_IP ..."
      sshGet ${H_IP} ${KEY_FILE} "sudo chown core.core -R /home/core"
      scp -i ${KEY_FILE}  -o StrictHostKeyChecking=no ${TOOLS} core@${H_IP}:/home/core/${TOOLS}
      scp -i ${KEY_FILE}  -o StrictHostKeyChecking=no ${VT} core@${H_IP}:/home/core/${Vt}
      if [[ -f libdnet.so.1.0.1 ]]; then
        scp -i ${KEY_FILE}  -o StrictHostKeyChecking=no libdnet.so.1.0.1 core@${H_IP}:/home/core/libdnet.so.1.0.1
      fi
      sshGet ${H_IP} ${KEY_FILE} "/home/core/${VT} ${TOOLS}"
      sshGet ${H_IP} ${KEY_FILE} "sudo rm -f /home/core/${VT}"
      sshGet ${H_IP} ${KEY_FILE} "sudo rm -f /home/core/${TOOLS}"
      sshGet ${H_IP} ${KEY_FILE} "sudo chown core.core -R /home/core"
    else
      echo "No such file: ${1}"
    fi
  else
    echo "Deploy VMware tools disable."
  fi
}

deployKey () {
  H_IP=${1}
  KEY_FILE=${2}
  if [[ -z ${KEY_FILE} ]]; then
    echo "Deploy key: insecure_ssh_key"
    scp -i insecure_ssh_key insecure_ssh_key core@${H_IP}:/home/core/.ssh/id_rsa
  else
    echo "Deploy key: ${KEY_FILE}"
    scp -i insecure_ssh_key ${KEY_FILE} core@${H_IP}:/home/core/.ssh/id_rsa
  fi
}

deployConfig () {
  H_IP=${1}
  KEY_FILE=${2}
  H_NAME=${3}
  if [[ ! -f cloud-config/${H_NAME}.yml ]]; then
    echo "File: cloud-config/${H_NAME}.yml not exits..."
    exit 1
  fi
  echo "Connect to ${H_IP} ..."
  # SSH_GET="ssh -i insecure_ssh_key -o StrictHostKeyChecking=no core@${H_IP}"
  sshGet ${H_IP} ${KEY_FILE} "sudo mkdir -p /storage"
  echo "Deploy /usr/share/oem/cloud-config.yml ..."
  # cat cloud-config/${H_NAME}.yml | ${SSH_GET} "cat > /home/core/${H_NAME}.yml"
  sshGet ${H_IP} ${KEY_FILE} "sudo chown core.core -R /home/core"
  cat cloud-config/${H_NAME}.yml | sshGet ${H_IP} ${KEY_FILE} "cat > /home/core/${H_NAME}.yml"
  # echo debig 1
  sshGet ${H_IP} ${KEY_FILE} "sudo cp /usr/share/oem/cloud-config.yml /home/core/old.yml"
  # echo debig 2
  sshGet ${H_IP} ${KEY_FILE} "sudo mv /home/core/${H_NAME}.yml /usr/share/oem/cloud-config.yml"
  # echo debig 3
}

if [[ ! -f ./keys/token ]]; then
  echo "Generate token keys/token ..."
  DISCOVERY_TOKEN_NEW=`curl -s https://discovery.etcd.io/new`
  echo $DISCOVERY_TOKEN_NEW > ./keys/token
  # DISCOVERY_TOKEN_FILE=
fi

if [[ $1 == "install" ]]; then
  if [[ -z $2 ]]; then
    echo "VMware Host is not set."
    exit 1
  fi
  if [[ -z $3 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi

  WF=${2}
  HF=${3}
  if [[ ! -f $WF ]]; then
    echo "File: ${WF} not exits..."
    exit 1
  fi
  if [[ ! -f $HF ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source ${WF}
  source ${HF}
  #chmod 0755 ./coreos_deploy_on_esxi.sh
  scp ./${WF} ${VM_SSH}:${DATASTORE_PATH}/${VM_HOST_NAME}.sh
  scp ./${HF} ${VM_SSH}:${DATASTORE_PATH}/${H_NAME}.sh
  scp ./coreos_deploy_on_esxi.sh ${VM_SSH}:${DATASTORE_PATH}/
  if [[ -z $4 ]]; then
    ssh ${VM_SSH} -C "cd ${DATASTORE_PATH}/ && ./coreos_deploy_on_esxi.sh ${VM_HOST_NAME} ${H_NAME}"
  else
    ssh ${VM_SSH} -C "cd ${DATASTORE_PATH}/ && ./coreos_deploy_on_esxi.sh ${VM_HOST_NAME} ${H_NAME} $4"
  fi

  VM_INFO=`ssh ${VM_SSH} -C "vim-cmd vmsvc/getallvms | grep ${H_NAME}"`
  VM_ID=`echo ${VM_INFO} | awk '{print $1}'`
  echo Added VM_ID=${VM_ID} to ${HF}
  echo "" >> ${HF}
  echo "ESXI=\"${WF}\"" >> ${HF}
  echo "VM_ID=${VM_ID}" >> ${HF}
  ssh ${VM_SSH} -C "rm ${DATASTORE_PATH}/${VM_HOST_NAME}.sh"
  ssh ${VM_SSH} -C "rm ${DATASTORE_PATH}/${H_NAME}.sh"
  ssh ${VM_SSH} -C "rm ${DATASTORE_PATH}/coreos_deploy_on_esxi.sh"
  exit 1
fi

if [[ $1 == "deploy" ]]; then
  if [[ -z $2 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi
  HF=${2}
  if [[ ! -f ${HF} ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source ${HF}
  if [[ ! -f ${ESXI} ]]; then
    echo "File: ${ESXI} not exits..."
    exit 1
  fi
  source ${ESXI}
  if [[ ! -f insecure_ssh_key ]]; then
    scp ${VM_SSH}:${DATASTORE_PATH}/${H_NAME}/insecure_ssh_key ./
    chmod 0600 ./insecure_ssh_key
  fi
  deployKey ${H_IP} ${KEY_FILE}
  deployConfig ${H_IP} insecure_ssh_key ${H_NAME}
  sshGet ${H_IP} insecure_ssh_key "sudo cp -R /home/core/.ssh /root/"
  # echo deploy tools
  deployTools ${H_IP} insecure_ssh_key ${TOOLS}
  echo "Reboot ${H_IP}"
  sshGet ${H_IP} insecure_ssh_key "sudo reboot"
  # sshGet ${H_IP} ${KEY_FILE} "sudo reboot"
  # systemctl stop system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service
  exit 1
fi

if [[ $1 == "update" ]]; then
  if [[ -z $2 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi
  HF=${2}
  if [[ ! -f $HF ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source ${HF}
  deployConfig ${H_IP} ${KEY_FILE} ${H_NAME}
  deployTools ${H_IP} ${KEY_FILE}  ${TOOLS}
  echo "Reboot ${H_IP}"
  sshGet ${H_IP} ${KEY_FILE} "sudo reboot"
  exit 1
fi

if [[ $1 == "gen" ]]; then
  if [[ -z $2 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi
  HF=${2}
  if [[ ! -f ${HF} ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source cluster01.sh
  source ${HF}
  if [[ -z ${DISCOVERY_TOKEN} ]]; then
    DISCOVERY_TOKEN=`cat ./keys/token`
  fi
  # echo "DISCOVERY_TOKEN $DISCOVERY_TOKEN"
  if [[ ! -z ${KEY_PUB_FILE} ]]; then
    KEY_PUB=`cat $KEY_PUB_FILE`
  fi
  if [[ -z ${KEY_PUB} ]]; then
    KEY_PUB=`cat insecure_ssh_key.pub`
  fi
  if [[ -z ${H_TZ} ]]; then
    H_TZ="UTC"
  fi
  # echo "KEY_PUB=$KEY_PUB"
  if [[ -z $H_METADATA ]]; then
    H_METADATA="region=ua,deis=no,router=no,cluster=yes,server=vmware02,host=$H_NAME"
  fi
  source cloud_config.sh
  exit 1
fi

if [[ $1 == "ssh" ]]; then
  if [[ -z $2 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi
  HF=${2}
  if [[ ! -f $HF ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source ${HF}
  if [[ -f ${KEY_FILE} ]]; then
    echo "Connect to ${H_IP}, key: ${KEY_FILE} ..."
    ssh -i ${KEY_FILE} -o StrictHostKeyChecking=no core@${H_IP}
  else
    if [[ -f ./insecure_ssh_key ]]; then
      echo "Connect to ${H_IP}, key: insecure_ssh_key ..."
      ssh -i ./insecure_ssh_key -o StrictHostKeyChecking=no core@${H_IP}
    else
      echo "Connect to ${H_IP} ..."
      ssh -o StrictHostKeyChecking=no core@${H_IP}
    fi
  fi
  exit 1
fi

if [[ $1 == "toolbox" ]]; then
  if [[ -z $2 ]]; then
    echo "CoreOS Host is not set."
    exit 1
  fi
  HF=${2}
  if [[ ! -f $HF ]]; then
    echo "File: ${HF} not exits..."
    exit 1
  fi
  source ${HF}
  sshGet ${H_IP} ${KEY_FILE} "/usr/bin/toolbox"
  exit 1
fi

help
